set nocompatible                       " be iMproved, required

" Source the plugins
so ~/.vim/plugins.vim

set laststatus=2
set backspace=indent,eol,start				 " Ensure backspace works like other editors
set number							               " Show line numbers

"-----------------Visuals-------------------"
set background=dark
syntax on
set cursorline
set termguicolors							" Set True Color (24-bit) support
colorscheme nord

"-----------------Search-------------------"
set hlsearch							" Highlight search results
set incsearch							" Incremental search - 'search as you type'

"-----------------Mappings-------------------"
"imap  = Insert Mode mapping
"nmap  = Normal Mode mapping
"vmap  = Visual Mode mapping

" Remove search highlighting
" nmap <Leader><space> :nohlsearch<cr>

"-----------------Auto-Commands-------------------"
augroup autosource
	" Clear the group (to avoid slowdown due to sourcing the file)
	autocmd!
	autocmd BufWritePost .vimrc source %			" Automatically source the .vimrc file on save
augroup END

