#
# Used for setting user's environment variables;
# it should not contain commands that produce output or assume the shell is attached to a tty.
# This file will always be sourced.

# Ensure that a non-login, non-interactive shell has a defined environment.
#if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
#  source "${ZDOTDIR:-$HOME}/.zprofile"
#fi

# If language environment is not set, make it so.
if [[ -z "$LANG" ]]; then
  export LANG='en_GB.UTF-8'
fi

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vi'
else
  export EDITOR='vi'
fi

# Pager settings
export PAGER='less'
# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'
# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

# Disable Next.js from collecting usage analytics
export NEXT_TELEMETRY_DISABLED=1
