# For many more options to customize oh-my-zsh take a look at the template
# The oh-my-zsh zshrc template is at ~/.oh-my-zsh/templates/zshrc.zsh-template

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="powerlevel10k/powerlevel10k"
# ZSH_THEME="39digits"

# The zsh-autosuggestions plugin can cause a very minor input lag.
# Run everything async to remove that (very small!) lag completely.
ZSH_AUTOSUGGEST_USE_ASYNC=true

# Official Plugins: ~/.oh-my-zsh/plugins/*
# Custom Plugins: ~/.oh-my-zsh/custom/plugins/
plugins=(zsh-nvm)
plugins+=(zsh-autosuggestions)
plugins+=(zsh-completions)
plugins+=(zsh-better-npm-completion)
# Note that zsh-syntax-highlighting must be the last plugin sourced.
plugins+=(zsh-syntax-highlighting)

# loads zsh-completions
autoload -U compinit && compinit

source $ZSH/oh-my-zsh.sh

###########################
## User configuration
##
## ENVIRONMENT VARIABLES:  .zshenv
## USER COMMANDS: .zprofile
## PATHS:  .zprofile
## ALIASES:  ~/.oh-my-zsh/custom/aliases.zsh
## For a full list of active aliases, run `alias`.
##

# We use the zsh-nvm plugin instead.
# export NVM_DIR="$HOME/.nvm"
#   [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
#   [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh