# For many more options to customize oh-my-zsh take a look at the template
# The oh-my-zsh zshrc template is at ~/.oh-my-zsh/templates/zshrc.zsh-template

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
# ZSH_THEME="39digits"

# The zsh-autosuggestions plugin can cause a very minor input lag.
# Run everything async to remove that (very small!) lag completely.
ZSH_AUTOSUGGEST_USE_ASYNC=true

# Official Plugins: ~/.oh-my-zsh/plugins/*
# Custom Plugins: ~/.oh-my-zsh/custom/plugins/
plugins=(zsh-nvm)
plugins+=(zsh-autosuggestions)
plugins+=(zsh-completions)
plugins+=(npm)
# Note that zsh-syntax-highlighting must be the last plugin sourced.
plugins+=(zsh-syntax-highlighting)

# loads zsh-completions
autoload -U compinit && compinit

source $ZSH/oh-my-zsh.sh

###########################
## User configuration
##
## ENVIRONMENT VARIABLES:  .zshenv
## USER COMMANDS:          .zprofile
## PATHS:                  .zprofile
## ALIASES:                ~/.oh-my-zsh/custom/aliases.zsh
## For a full list of active aliases, run `alias`.
##

# We use the zsh-nvm plugin instead.
# export NVM_DIR="$HOME/.nvm"
#   [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
#   [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Finally, source oh my posh
eval "$(oh-my-posh init zsh --config $HOME/.config/oh-my-posh/39digits.omp.json)"
